# Generated by Django 4.0.4 on 2022-06-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),

    ]
