# Generated by Django 4.0.4 on 2022-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
