# Generated by Django 4.0.4 on 2022-05-31 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_publication_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_roll', models.IntegerField()),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=200)),
                ('student_mob_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('student_email', models.EmailField(max_length=254)),
                ('student_sem', models.IntegerField()),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('student_dob', models.DateField()),
                ('student_password', models.CharField(max_length=50)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
