# Generated by Django 4.0.4 on 2022-06-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_roll',
            field=models.IntegerField(unique=True),
        ),

    ]
