# Generated by Django 4.0.4 on 2022-06-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_students_student_roll_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_class_no', models.CharField(max_length=30, unique=True)),
                ('book_edition', models.DateField()),
                ('received_by', models.CharField(max_length=200)),
                ('book_bill_date', models.DateField()),
                ('book_bill_no', models.IntegerField()),
                ('book_pages', models.IntegerField()),
                ('book_price', models.IntegerField()),
                ('book_date_of_entry', models.DateField()),
                ('book_location', models.CharField(max_length=20)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.author')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.publication')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
