# Generated by Django 4.0.4 on 2022-06-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.publication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.students')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
    ]
