# Generated by Django 4.0.4 on 2022-07-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('penalty_amount', models.IntegerField()),
                ('penalty_pay', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.students')),
            ],
            options={
                'db_table': 'penalty',
            },
        ),
    ]
