# Generated by Django 4.0.6 on 2022-08-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_book_lost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('demand_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.students')),
            ],
            options={
                'db_table': 'demand',
            },
        ),
    ]
